import type { Project, Freelancer } from "@/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p-1001",
    title: "Senior React Developer für FinTech-Produkt (m/w/d)",
    company: "Nordstern Banking GmbH",
    companyVerified: true,
    location: "Frankfurt am Main",
    postalCode: "60311",
    region: "Hessen",
    country: "DE",
    workMode: "remote",
    budgetMin: 90,
    budgetMax: 110,
    budgetUnit: "hour",
    duration: "long",
    durationMonths: 12,
    contractType: "freelance",
    startDate: "2026-06-15",
    publishedAt: "2026-05-19",
    industry: "Zahlungsverkehr & FinTech",
    description:
      "Für die Weiterentwicklung unseres Trading-Frontends suchen wir einen erfahrenen React-Entwickler mit TypeScript-Kenntnissen. Mind. 6 Jahre Berufserfahrung, idealerweise Background im Finanzsektor.",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Jest"],
    applicants: 14,
    isTopProject: true,
  },
  {
    id: "p-1002",
    title: "SAP S/4HANA Berater – Migration & Rollout",
    company: "Industriewerke Süd AG",
    companyVerified: true,
    location: "Stuttgart",
    postalCode: "70173",
    region: "Baden-Württemberg",
    country: "DE",
    workMode: "hybrid",
    budgetMin: 1100,
    budgetMax: 1350,
    budgetUnit: "day",
    duration: "long",
    durationMonths: 9,
    contractType: "werkvertrag",
    startDate: "2026-06-01",
    publishedAt: "2026-05-20",
    industry: "SAP & ERP",
    description:
      "Begleitung eines konzernweiten S/4HANA-Rollouts in der Produktion. Schwerpunkte: PP/MM, Cutover-Planung, Key-User-Schulungen.",
    skills: ["SAP S/4HANA", "SAP PP", "SAP MM", "Projektleitung"],
    applicants: 6,
    isUrgent: true,
  },
  {
    id: "p-1003",
    title: "DevOps Engineer – AWS/Kubernetes (Vertrag 6 Monate+)",
    company: "Allwetter Versicherung",
    companyVerified: true,
    location: "Köln",
    postalCode: "50667",
    region: "Nordrhein-Westfalen",
    country: "DE",
    workMode: "remote",
    budgetMin: 85,
    budgetMax: 105,
    budgetUnit: "hour",
    duration: "medium",
    durationMonths: 6,
    contractType: "freelance",
    startDate: "2026-06-10",
    publishedAt: "2026-05-18",
    industry: "Cloud & DevOps",
    description:
      "Aufbau einer EKS-basierten Plattform für Microservices, GitOps mit ArgoCD, Observability mit Prometheus/Grafana.",
    skills: ["AWS", "Kubernetes", "Terraform", "ArgoCD", "Prometheus"],
    applicants: 22,
  },
  {
    id: "p-1004",
    title: "Data Scientist (NLP) für KI-Suchprodukt",
    company: "Helios Search Labs GmbH",
    companyVerified: true,
    location: "Berlin",
    postalCode: "10115",
    region: "Berlin",
    country: "DE",
    workMode: "remote",
    budgetMin: 95,
    budgetMax: 120,
    budgetUnit: "hour",
    duration: "medium",
    durationMonths: 6,
    contractType: "dienstvertrag",
    startDate: "2026-06-20",
    publishedAt: "2026-05-21",
    industry: "Data Science & KI",
    description:
      "Entwicklung und Feintuning eines LLM-basierten Such- und Retrieval-Stacks. Erfahrung mit RAG, Vector-Datenbanken und Embeddings vorausgesetzt.",
    skills: ["Python", "Machine Learning", "PyTorch", "RAG", "Vector DB"],
    applicants: 9,
    isTopProject: true,
  },
  {
    id: "p-1005",
    title: "Cyber Security Consultant – ISO 27001 Audit",
    company: "Bundesdruck Logistik GmbH",
    companyVerified: true,
    location: "Hamburg",
    postalCode: "20095",
    region: "Hamburg",
    country: "DE",
    workMode: "onsite",
    budgetMin: 1200,
    budgetMax: 1450,
    budgetUnit: "day",
    duration: "short",
    durationMonths: 3,
    contractType: "werkvertrag",
    startDate: "2026-06-05",
    publishedAt: "2026-05-17",
    industry: "Cyber Security",
    description:
      "Durchführung interner ISO 27001-Audits, Erstellung des Audit-Berichts, Begleitung der Re-Zertifizierung.",
    skills: ["ISO 27001", "Audit", "Risk Assessment", "Cyber Security"],
    applicants: 4,
  },
  {
    id: "p-1006",
    title: "Senior Flutter Developer – Banking-App",
    company: "Mobilbank Direkt AG",
    companyVerified: true,
    location: "München",
    postalCode: "80331",
    region: "Bayern",
    country: "DE",
    workMode: "remote",
    budgetUnit: "hour",
    rateUndisclosed: true,
    duration: "long",
    durationMonths: 12,
    contractType: "anue",
    startDate: "2026-07-01",
    publishedAt: "2026-05-16",
    industry: "Mobile (iOS / Android)",
    description:
      "Weiterentwicklung der nativen Mobile-Banking-App. Fokus auf Performance, Sicherheit (PSD2/SCA), Biometrie.",
    skills: ["Flutter", "Dart", "iOS", "Android", "REST API"],
    applicants: 18,
  },
  {
    id: "p-1007",
    title: "Cloud Architect – Migration Azure (Public Sector)",
    company: "Stadtwerke Rheinland",
    companyVerified: true,
    location: "Düsseldorf",
    postalCode: "40213",
    region: "Nordrhein-Westfalen",
    country: "DE",
    workMode: "hybrid",
    budgetMin: 1000,
    budgetMax: 1250,
    budgetUnit: "day",
    duration: "long",
    durationMonths: 9,
    contractType: "werkvertrag",
    startDate: "2026-06-15",
    publishedAt: "2026-05-20",
    industry: "Bundes-, Landes- & Kommunalverwaltung",
    description:
      "Konzeption der Migrationsstrategie für mehrere Geschäftsanwendungen nach Azure (IaaS/PaaS). Erfahrung im öffentlichen Sektor wünschenswert.",
    skills: ["Azure", "Cloud Architecture", "Terraform", "IT-Grundschutz"],
    applicants: 7,
  },
  {
    id: "p-1008",
    title: "UX/UI Designer für SaaS-Plattform (B2B)",
    company: "Procura Software GmbH",
    companyVerified: true,
    location: "Leipzig",
    postalCode: "04109",
    region: "Sachsen",
    country: "DE",
    workMode: "remote",
    budgetMin: 70,
    budgetMax: 90,
    budgetUnit: "hour",
    duration: "medium",
    durationMonths: 6,
    contractType: "freelance",
    startDate: "2026-06-01",
    publishedAt: "2026-05-18",
    industry: "IT & Softwareentwicklung",
    description:
      "Überarbeitung des bestehenden Dashboards (Design-System, Komponentenbibliothek in Figma), enge Zusammenarbeit mit Frontend-Team.",
    skills: ["Figma", "UX/UI Design", "Design Systems", "Prototyping"],
    applicants: 31,
  },
];

export const MOCK_FREELANCERS: Freelancer[] = [
  {
    id: "f-2001",
    fullName: "Dr. Lena Hofmann",
    title: "Senior Cloud Solution Architect",
    initials: "LH",
    location: "München",
    region: "Bayern",
    country: "DE",
    workMode: "hybrid",
    availability: "1month",
    hourlyRateMin: 120,
    hourlyRateMax: 145,
    yearsExperience: 14,
    rating: 4.9,
    reviewsCount: 38,
    industry: "Cloud & DevOps",
    bio: "AWS- und Azure-zertifizierte Lösungsarchitektin mit Fokus auf hochskalierbare Plattformen im regulierten Umfeld (Finanz- und Versicherungswesen).",
    skills: ["AWS", "Azure", "Kubernetes", "Terraform", "Microservices"],
    languages: ["Deutsch", "Englisch"],
    isVerified: true,
    isTopRated: true,
    responseTimeHours: 4,
  },
  {
    id: "f-2002",
    fullName: "Markus Reinhardt",
    title: "Senior SAP S/4HANA Consultant",
    initials: "MR",
    location: "Walldorf",
    region: "Baden-Württemberg",
    country: "DE",
    workMode: "remote",
    availability: "immediately",
    hourlyRateMin: 130,
    hourlyRateMax: 160,
    yearsExperience: 18,
    rating: 4.8,
    reviewsCount: 52,
    industry: "SAP & ERP",
    bio: "Langjähriger SAP-Berater mit Schwerpunkt Logistik (MM/PP). Erfahrung in Greenfield- und Brownfield-Migrationen mittelständischer Konzerne.",
    skills: ["SAP S/4HANA", "SAP MM", "SAP PP", "ABAP", "Fiori"],
    languages: ["Deutsch", "Englisch"],
    isVerified: true,
    isTopRated: true,
    responseTimeHours: 6,
  },
  {
    id: "f-2003",
    fullName: "Sophie Berger",
    title: "Senior Full-Stack Developer (React / Node.js)",
    initials: "SB",
    location: "Berlin",
    region: "Berlin",
    country: "DE",
    workMode: "remote",
    availability: "1month",
    hourlyRateMin: 95,
    hourlyRateMax: 115,
    yearsExperience: 9,
    rating: 4.9,
    reviewsCount: 24,
    industry: "IT & Softwareentwicklung",
    bio: "Spezialisiert auf produktnahe Frontend-Architektur, Design-Systeme und API-Design. Sehr starker Kommunikator zwischen Produkt und Engineering.",
    skills: ["React", "TypeScript", "Next.js", "Node.js", "PostgreSQL"],
    languages: ["Deutsch", "Englisch", "Französisch"],
    isVerified: true,
    responseTimeHours: 3,
  },
  {
    id: "f-2004",
    fullName: "Tobias Krüger",
    title: "Cyber Security Architect / ISO 27001 Lead Auditor",
    initials: "TK",
    location: "Hamburg",
    region: "Hamburg",
    country: "DE",
    workMode: "hybrid",
    availability: "3months",
    hourlyRateMin: 135,
    hourlyRateMax: 165,
    yearsExperience: 16,
    rating: 4.8,
    reviewsCount: 31,
    industry: "Cyber Security",
    bio: "ISMS-Implementierung, BCM und technische Security-Architektur. Erfahrung mit BSI IT-Grundschutz und KRITIS-Pflichten.",
    skills: ["ISO 27001", "BSI IT-Grundschutz", "Risk Management", "SOC"],
    languages: ["Deutsch", "Englisch"],
    isVerified: true,
    isTopRated: true,
    responseTimeHours: 12,
  },
  {
    id: "f-2005",
    fullName: "Dr. Jonas Albrecht",
    title: "Lead Data Scientist (NLP / ML)",
    initials: "JA",
    location: "Heidelberg",
    region: "Baden-Württemberg",
    country: "DE",
    workMode: "remote",
    availability: "immediately",
    hourlyRateMin: 110,
    hourlyRateMax: 140,
    yearsExperience: 11,
    rating: 4.9,
    reviewsCount: 27,
    industry: "Data Science & KI",
    bio: "Promotion in Computational Linguistics, langjährige Produktionserfahrung mit modernen LLMs, RAG-Pipelines und MLOps.",
    skills: ["Python", "PyTorch", "RAG", "MLOps", "Vector DB"],
    languages: ["Deutsch", "Englisch"],
    isVerified: true,
    isTopRated: true,
    responseTimeHours: 5,
  },
  {
    id: "f-2006",
    fullName: "Anna Walter",
    title: "Senior UX/UI Designerin",
    initials: "AW",
    location: "Köln",
    region: "Nordrhein-Westfalen",
    country: "DE",
    workMode: "remote",
    availability: "1month",
    hourlyRateMin: 85,
    hourlyRateMax: 105,
    yearsExperience: 10,
    rating: 4.9,
    reviewsCount: 41,
    industry: "IT & Softwareentwicklung",
    bio: "Schwerpunkt auf B2B-SaaS und komplexen Dashboards. Aufbau und Pflege skalierbarer Design-Systeme in Figma.",
    skills: ["Figma", "UX/UI Design", "Design Systems", "Accessibility"],
    languages: ["Deutsch", "Englisch"],
    isVerified: true,
    responseTimeHours: 4,
  },
  {
    id: "f-2007",
    fullName: "Khaled El-Sayed",
    title: "Senior DevOps Engineer",
    initials: "KE",
    location: "Frankfurt am Main",
    region: "Hessen",
    country: "DE",
    workMode: "remote",
    availability: "immediately",
    hourlyRateMin: 95,
    hourlyRateMax: 120,
    yearsExperience: 12,
    rating: 4.8,
    reviewsCount: 22,
    industry: "Cloud & DevOps",
    bio: "GitOps-Spezialist mit tiefer Erfahrung in Kubernetes, ArgoCD, Tekton und Terraform. Hands-on im regulierten Umfeld (BaFin).",
    skills: ["Kubernetes", "ArgoCD", "Terraform", "AWS", "GitLab CI"],
    languages: ["Deutsch", "Englisch", "Arabisch"],
    isVerified: true,
    responseTimeHours: 6,
  },
  {
    id: "f-2008",
    fullName: "Christina Vogt",
    title: "Senior Projektleiterin / Scrum Master",
    initials: "CV",
    location: "Stuttgart",
    region: "Baden-Württemberg",
    country: "DE",
    workMode: "hybrid",
    availability: "1month",
    hourlyRateMin: 110,
    hourlyRateMax: 135,
    yearsExperience: 15,
    rating: 4.9,
    reviewsCount: 47,
    industry: "Beratung & Management",
    bio: "Skalierte Agilität (SAFe), klassische und hybride Projektleitung in der Automotive- und Fertigungsindustrie.",
    skills: ["Scrum", "SAFe", "Projektleitung", "Stakeholder-Management"],
    languages: ["Deutsch", "Englisch"],
    isVerified: true,
    isTopRated: true,
    responseTimeHours: 4,
  },
];
