export const TOP_SKILLS = [
  "React",
  "TypeScript",
  "Java",
  "Python",
  "SAP S/4HANA",
  "AWS",
  "Azure",
  "Kubernetes",
  "Docker",
  "Node.js",
  "Angular",
  "Vue.js",
  "Salesforce",
  "Power BI",
  "Tableau",
  "Snowflake",
  "Databricks",
  "Terraform",
  "Ansible",
  "PostgreSQL",
  "MongoDB",
  "GraphQL",
  "REST API",
  "Microservices",
  "DevOps",
  "Cyber Security",
  "Penetration Testing",
  "ISO 27001",
  "Scrum",
  "Projektleitung",
  "Business Analyse",
  "UX/UI Design",
  "Figma",
  "Machine Learning",
  "TensorFlow",
  "PyTorch",
  "Data Engineering",
  "Apache Spark",
  "ETL",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "Flutter",
  "iOS / Swift",
  "Android / Kotlin",
] as const;

export const COUNTRIES = [
  { value: "DE", label: "Deutschland" },
  { value: "AT", label: "Österreich" },
  { value: "CH", label: "Schweiz" },
] as const;

export const REGIONS_BY_COUNTRY: Record<"DE" | "AT" | "CH", readonly string[]> = {
  DE: [
    "Baden-Württemberg",
    "Bayern",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hessen",
    "Mecklenburg-Vorpommern",
    "Niedersachsen",
    "Nordrhein-Westfalen",
    "Rheinland-Pfalz",
    "Saarland",
    "Sachsen",
    "Sachsen-Anhalt",
    "Schleswig-Holstein",
    "Thüringen",
  ],
  AT: [
    "Wien",
    "Niederösterreich",
    "Oberösterreich",
    "Steiermark",
    "Tirol",
    "Salzburg",
    "Vorarlberg",
    "Kärnten",
    "Burgenland",
  ],
  CH: [
    "Zürich",
    "Bern",
    "Basel-Stadt",
    "Basel-Landschaft",
    "Genf",
    "Waadt",
    "Luzern",
    "St. Gallen",
    "Aargau",
    "Tessin",
    "Zug",
  ],
};

export const CITIES = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt am Main",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Hannover",
  "Nürnberg",
  "Bremen",
  "Karlsruhe",
  "Mannheim",
  "Walldorf",
  "Heidelberg",
  "Wien",
  "Graz",
  "Linz",
  "Salzburg",
  "Zürich",
  "Genf",
  "Basel",
  "Bern",
] as const;

export const PROJECT_MONTHS = [
  { value: 1, label: "1 Monat" },
  { value: 3, label: "3 Monate" },
  { value: 6, label: "6 Monate" },
  { value: 9, label: "9 Monate" },
  { value: 12, label: "12 Monate" },
  { value: 18, label: "18 Monate" },
  { value: 24, label: "24 Monate +" },
] as const;

export const MONTHS_DE = [
  "Januar",
  "Februar",
  "März",
  "April",
  "Mai",
  "Juni",
  "Juli",
  "August",
  "September",
  "Oktober",
  "November",
  "Dezember",
] as const;
